# Generated by Django 3.0.6 on 2020-06-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('favorite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sitekind', models.CharField(choices=[('blog', 'ブログサイト'), ('promo', 'プロモーションサイト'), ('portfo', 'ポートフォリオサイト'), ('ecsite', 'ECサイト'), ('corp', 'コーポレートサイト'), ('recru', 'リクルートサイト'), ('landing', 'ランディングページ')], default='blog', max_length=20)),
                ('siteurl', models.URLField(max_length=100)),
                ('gooduser', models.CharField(max_length=255)),
                ('postuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swank.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swank.SiteModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swank.UserModel')),
            ],
        ),
    ]
