# Generated by Django 3.0.6 on 2020-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swank', '0002_sitemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='gooduser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
