# Generated by Django 3.0.6 on 2020-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swank', '0003_auto_20200602_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='favorite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
